server:
  port: 9002
application:
  version: ${version}
  headers:
    authorization: "authorization"
    userId: "user-id"
  session-filter:
    unsecure-routes:
      - path: "/api/v1/users"
        method: "POST"
  services:
    user-service:
      uri: http://\${USER_HOST:localhost}:9001
      tokenPath: "/api/v1/tokens"
    game-service:
      uri: http://\${GAME_HOST:localhost}:9000
spring:
  rabbitmq:
    host: \${RABBIT_HOST:localhost}
    port: \${RABBIT_PORT:5672}
    username: \${RABBIT_USER:guest}
    password: \${RABBIT_PASSWORD:guest}
  rsocket:
    server:
      port: 9003
      mapping-path: /rsocket
      transport: websocket
  cloud:
    gateway:
      routes:
#        USER SERVICE
        - id: get-current-user
          uri: \${application.services.user-service.uri}
          predicates:
            - Path=/api/v1/user/current
            - Method=GET
        - id: user-create
          uri: \${application.services.user-service.uri}
          predicates:
            - Path=/api/v1/users
            - Method=POST
        - id: users-get
          uri: \${application.services.user-service.uri}
          predicates:
            - Path=/api/v1/users
            - Method=GET
            - Query=ids
#        USER SERVICE END
#        GAME SERVICE
        - id: game-join
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/game/join
            - Method=POST
        - id: game-create
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/games
            - Method=POST
        - id: game-get
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/games/{id}
            - Method=GET
        - id: game-ws
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/ws/**
        - id: game-words-add
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/words
            - Method=POST
        - id: game-start-game
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/games/{gameId}/startGame
            - Method=POST
        - id: game-start-round
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/games/{gameId}/rounds
            - Method=POST
        - id: game-get-rounds
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/games/{gameId}/rounds
            - Method=GET
            - Query=limit
            - Query=sort
        - id: game-next-round
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/games/{gameId}/rounds/{roundId}/finishCurrentAndStartNewExplanation
            - Method=POST
        - id: game-finish-round
          uri: \${application.services.game-service.uri}
          predicates:
            - Path=/api/v1/games/{gameId}/rounds/{roundId}/finish
            - Method=POST
#        GAME SERVICE END
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
