server:
  port: 9002
hat:
  headers:
    authorization: "authorization"
    userId: "user-id"
  user-service:
    host: http://${APP_HOST:localhost}:9001
    tokenUrlPath: "/api/v1/token"
spring:
  cloud:
    gateway:
      routes:
        - id: get-current-user
          uri: http://${APP_HOST:localhost}:9001
          predicates:
            - Path=/api/v1/user/current
            - Method=GET
        - id: user-create
          uri: http://${APP_HOST:localhost}:9001
          predicates:
            - Path=/api/v1/users
            - Method=POST
        - id: game-join
          uri: http://${APP_HOST:localhost}:9000
          predicates:
            - Path=/api/v1/game/join
            - Method=POST
        - id: game-create
          uri: http://${APP_HOST:localhost}:9000
          predicates:
            - Path=/api/v1/games
            - Method=POST
