name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  packages: read

jobs:
  publish-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Before Install
        run: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Script
        run: |
          ./gradlew build --debug
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
#      - name: Upload code coverage
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
